= Story of The Revenge of Kalista
Julien Bernard <julien.bernard@univ-fcomte.fr>; Léo Mercier
v0.5
:toc:
:homepage: https://akagoria.github.io/
:stem: latexmath
:source-highlighter: coderay
:xrefstyle: full

This document describes the story of _The Revenge of Kalista_. It is based on the link:world_description.html[description of Akagoria].

== Introduction
A really long time ago, a really bad witch born. At the beginning she was a happy child but the murder of her parents traumatised her. 
When she asked help to the wizards, they refused, they were not interrested by a weak child. She decided to destroy this horrible world.
She stoole an ancient ritual. She ask to the evil god Ike to become the one that will destroy the world. She received a lot of power and she began to destroy everything. 
The wizards reunited and created a spell to emprison Kalista forever.
 
== Part 1: Arraband
Hundreds and hundreds of years after his imprisonment; Kalista is finally free. 

== Part 2: Elatan

== Part 3: Inichke

== Part 4: Orta

== Part 5: Uchun

== Conclusion